# Generated by Django 4.2.5 on 2023-09-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False),
        ),
    ]
