# Generated by Django 4.2.5 on 2023-09-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_prices_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='cur',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
